import { AI_MODEL, GEMINI_API_KEY } from "./config";

export type GeneratedContent = {
  title: string;
  slug: string;
  excerpt: string;
  seoTitle: string;
  seoDescription: string;
  content: string;
  faq: Array<{ question: string; answer: string }>;
};

export async function generateContent(prompt: string): Promise<GeneratedContent> {
  if (!GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY is not configured");
  }

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${AI_MODEL}:generateContent?key=${GEMINI_API_KEY}`;

  const response = await fetch(endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [
            { text: prompt }
          ]
        }
      ],
      generationConfig: {
        responseMimeType: "application/json",
      }
    }),
  });

  if (!response.ok) {
    const error = await response.json();
    console.error("Gemini API error:", error);
    throw new Error(`Failed to generate content: ${response.statusText}`);
  }

  const data = await response.json();
  
  console.log("--- AI GENERATOR: RAW DATA ---");
  console.log(JSON.stringify(data, null, 2));

  const text = data.candidates[0]?.content?.parts[0]?.text;

  if (!text) {
    console.error("AI GENERATOR ERROR: No text in candidates", data);
    throw new Error("No content generated by Gemini");
  }

  console.log("--- AI GENERATOR: GENERATED TEXT ---");
  console.log(text);

  try {
    return JSON.parse(text) as GeneratedContent;
  } catch (e) {
    console.error("AI GENERATOR ERROR: JSON parse failed", text);
    throw new Error("AI response was not valid JSON");
  }
}
